apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
        - name: resume-container
          image: avishkarlakade/resumecraft:latest
          ports:
            - containerPort: 3000
