apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-deployment
  namespace: default
  labels:
    app: resume-builder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-builder
  template:
    metadata:
      labels:
        app: resume-builder
    spec:
      containers:
      - name: resume-builder
        image: avishkarlakade/resume-builder:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
