apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: avishkarlakade/ai-resume-builder:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "your-mongodb-uri-here"
            - name: ANOTHER_ENV_VAR
              value: "some-value"
