apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app
  labels:
    app: resume-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
        - name: resume-container
          image: avishkarairesume.azurecr.io/resume-app:latest
          ports:
            - containerPort: 3000

