apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-builder
  template:
    metadata:
      labels:
        app: resume-builder
    spec:
      containers:
        - name: resume-builder
          image: avishkarlakade/ai-resume-builder:latest
          ports:
            - containerPort: 3000
