apiVersion: v1
kind: Secret
metadata:
  name: resume-env
type: Opaque
stringData:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_Z3VpZGVkLWlndWFuYS04OS5jbGVyay5hY2NvdW50cy5kZXYk
  CLERK_SECRET_KEY: sk_test_S78DSKajyGHee7mCWx6VCtJrnQTdwwtVdoNiC17cU0

  NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up

  MONGODB_URL: mongodb+srv://avishkar:Avishkar%403119@meetingapp.kk3gqmd.mongodb.net/

  GEMINI_API_KEY: AIzaSyB77uZDnm4PEcWM5WubKQSIs1NmgFN5ILU

  BASE_URL: http://localhost:3000
