apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: LoadBalancer  # This works with minikube tunnel
  selector:
    app: resume-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
