apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - avishkarresume.cloudns.net  # ✅ Your actual domain
    secretName: resume-app-tls     # Will be created by cert-manager
  rules:
  - host: avishkarresume.cloudns.net  # ✅ Your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resume-app-service  # ✅ Match this to your actual service name from service.yaml
            port:
              number: 80
